config/routes.rb
Rails.application.routes.draw do

  devise_for :applicants,controllers: { sessions: 'applicants/sessions', registrations: 'applicants/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :leasing_agents, controllers: { sessions: 'leasing_agents/sessions', registrations: 'leasing_agents/registrations'}


  resources :waitlists
  resources :applications
  resources :properties
  resources :admins
  resources :applicants
  resources :leasing_agents
  root 'home#index'
  devise_scope :leasing_agents do
    get '/users/sign_out' => 'devise/sessions#destroy'
    end
    devise_scope :admin do
      get '/admin/sign_out' => 'devise/sessions#destroy'
    end
  devise_scope :applicants do
    get '/applicants/sign_out' => 'devise/sessions#destroy'
  end


  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'getallProperties' => 'properties#getallproperties', :as => :getallproperties
  get 'tenantcheckin' => 'properties#checkin', :as => :tenantcheckin
  get 'tenantcheckout' => 'properties#checkout', :as => :tenantcheckout
  get 'tenantapproval' => 'properties#approval', :as => :tenantapproval
  get '/show_leasing_agents' => 'admins#show_leasing_agents', :as => 'show_leasing_agents'
  get '/show_properties' => 'admins#show_properties', :as => 'show_properties'
  get '/show_applicants' => 'admins#show_applicants', :as => 'show_applicants'
  get '/show_applications' => 'admins#show_applications', :as => 'show_applications'
  get '/add_applications' => 'applications#admin_application', :as => 'add_applications'
  get '/add_properties' => 'properties#admin_properties', :as => 'add_properties'

  get 'getproperties' => 'leasing_agents#getproperties', :as => :getproperties
  get 'checkin' => 'applications#checkin', :as => :checkin
  get 'checkout' => 'applications#checkout', :as => :checkout
  get 'reject' => 'applications#reject', :as => :reject

  get 'moveout'=> 'properties#moveout', :as => :moveout

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:

    user ||= Admin.new # guest user (not logged in)
       if user.admin_role?
         can :manage, :all
         can :access, :rails_admin       # only allow admin users to access Rails Admin
         can :manage, :dashboard
         end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/applicant.rb
class Applicant < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :applications
  has_many :properties
  validates :name, :phone_number, presence: true
end

app/models/application.rb
class Application < ApplicationRecord
  belongs_to :property , optional: true
  belongs_to :applicant
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/leasing_agent.rb
class LeasingAgent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties
  validates :name, :email, :phone_number, presence: true
  validates :password, presence: true, :if =>:password


end

app/models/property.rb
class Property < ApplicationRecord
  has_many :applications
  has_many :applicants, through: :applications, dependent: :destroy
  belongs_to :leasing_agent, optional: true
  validates :name, :address, :size, :terms_available, :earliest_start_time, :application_fee, :monthly_rent, :occupied_by, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_admin, only: %i[ show edit update destroy ]

  # GET /admins or /admins.json
  def index
    @admins = Admin.all
  end

  # GET /admins/1 or /admins/1.json
  def show
  end

  # GET /admins/new
  def new
    @admin = Admin.new
  end

  # GET /admins/1/edit
  def edit
  end

  # POST /admins or /admins.json
  def create
    @admin = Admin.new(admin_params)

    respond_to do |format|
      if @admin.save
        format.html { redirect_to @admin, notice: "Admin was successfully created." }
        format.json { render :show, status: :created, location: @admin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admins/1 or /admins/1.json
  def update
    respond_to do |format|
      if @admin.update(admin_params)
        format.html { redirect_to @admin, notice: "Admin was successfully updated." }
        format.json { render :show, status: :ok, location: @admin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @admin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admins/1 or /admins/1.json
  def destroy
    @admin.destroy
    respond_to do |format|
      format.html { redirect_to admins_url, notice: "Admin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def show_leasing_agents
    @leasing_agents = LeasingAgent.all
  end

  def show_applicants
    @applicants = Applicant.all
  end

  def show_applications
    @applications = Application.all
  end

  def show_properties
    @properties = Property.all
    @applications = Application.all
  end


  private
    # Use callbacks to share common setup or constraints between actions.
  def set_admin
    @admin = Admin.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def admin_params
    params.require(:admin).permit(:admin_id, :name, :password, :email_address, :phone_number)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if admin_signed_in?
      redirect_to admins_path

    elsif applicant_signed_in?
      redirect_to applicants_path

    elsif leasing_agent_signed_in?
      redirect_to leasing_agents_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create], :raise => false

  def new
  end

  def create
    user = User.find_by_email_address(params[:email_address])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url
    else
      flash.now[:alert] = "Email or password is invalid"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/applicants_helper.rb
module ApplicantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper

  end

app/helpers/leasing_agents_helper.rb
module LeasingAgentsHelper
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/admins/_form.html.erb
<%= form_with(model: admin) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
        <% admin.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>


  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->


<p align="right" class="navbar-text pull-left">
<p align="right" class="navbar-text pull-left">
  <% if admin_signed_in? %>
    <%= link_to "Sign out", destroy_admin_session_path, method: :get, :class => 'navbar-link'  %>
  <%end %>
</p>

<h1>Admin Panel</h1>
Name: <%= current_admin.name %><br>
Email: <%=  current_admin.email %><br>
<br>
<br>
</p>
<h1>Admin's Dashboard</h1>
<table>
  <th><strong>Admin Rights</strong></th>

  <tr><td><%= link_to 'Edit Profile', edit_admin_path(current_admin) %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Leasing Agent</strong></td><tr>
  <tr><td><%= link_to 'Add Leasing Agent', new_leasing_agent_path %></td></tr>
  <tr><td><%= link_to 'View Leasing Agents (Details/Edit/Delete)', show_leasing_agents_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Applications</strong></td><tr>
  <tr><td><%= link_to 'Add Applications', add_applications_path %></tr>
  <tr><td><%= link_to 'View Applications (Details/Edit/Delete)', show_applications_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
  <tr><td><strong>Applicants</strong></td><tr>
  <tr><td><%= link_to 'Add Applicant', new_applicant_path %></td></tr>
  <tr><td><%= link_to 'View Applicant (Details/Edit/Delete)', show_applicants_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td>
  <tr><td><strong>Properties</strong></td><tr>
  <tr><td><%= link_to 'Add Properties', add_properties_path %></td></tr>
  <tr><td><%= link_to 'View Properties (Details/Edit/Delete)', show_properties_path %></td></tr>
  <tr><td></td><tr>
  <tr><td></td><tr>
</table>
<br>

app/views/admins/new.html.erb
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.registerable? && controller_name != 'registrations' %>
<!--  <%#= link_to "Sign up", new_registration_path(resource_name) %><br />-->
<%# end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @admin.password %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @admin.email_address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @admin.phone_number %>
</p>

<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/admins/show_applicants.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email address</th>
    <th>Phone number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @applicants.each do |applicant| %>
    <tr>
      <td><%= applicant.name %></td>
      <td><%= applicant.email %></td>
      <td><%= applicant.phone_number %></td>
      <td><%= link_to 'Edit', edit_applicant_path(applicant) %></td>
      <td><%= link_to 'Destroy', applicant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', admins_path %>

app/views/admins/show_applications.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th>Applicant Name</th>
    <th>Property id</th>
    <th>Status</th>
    <th>id</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @applications.each do |application| %>
    <tr>
      <td><%= Applicant.find(application.applicant_id).name %></td>
      <td><%= Property.find(application.property_id).name %></td>
      <td><%= application.status %></td>
      <td><%= application.id %></td>
      <td><%= link_to 'Edit', edit_application_path(application) %></td>
      <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', admins_path %>

app/views/admins/show_leasing_agents.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th>Email address</th>
    <th>Phone number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @leasing_agents.each do |leasing_agent| %>
    <tr>
      <td><%= leasing_agent.name %></td>
      <td><%= leasing_agent.email %></td>
      <td><%= leasing_agent.phone_number %></td>
      <td><%= link_to 'Edit', edit_leasing_agent_path(leasing_agent) %></td>
      <td><%= link_to 'Destroy', leasing_agent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<br>
<%= link_to 'Back', admins_path %>

app/views/admins/show_properties.html.erb
<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Size</th>
      <th>Features: Laundry</th>
      <th>Features: Parking</th>
      <th>Features: Pets</th>
      <th>Terms available</th>
      <th>Earliest Start Date</th>
      <th>Monthly Rent</th>
      <th>Application fee</th>
      <th>Occupied By</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.size %></td>
        <td><%= property.features_laundry %></td>
        <td><%= property.features_parking %>
        <td><%= property.features_pets %></td>
        <td><%= property.terms_available %></td>
        <td><%= property.earliest_start_time %></td>
        <td><%= property.monthly_rent %></td>
        <td><%= property.application_fee %></td>
        <td><%= property.occupied_by %></td>
		    <td><%= link_to 'Show', property %></td>
		    <td><%= link_to 'Edit', edit_property_path(property) %></td>
		    <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if admin_signed_in? %>
  <h1> Applications for all Properties</h1>
  <br>

  <table>
    <thead>
    <tr>
      <th>Applicant Name</th>
      <th>Date time</th>
      <th>Property</th>
      <th>Status</th>
      </div>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= Applicant.find(application.applicant_id).name %></td>
        <td><%= application.date_time %></td>
        <td><%= Property.find(application.property_id).name %></td>
        <td><%= application.status %></td>
        <td><%= link_to 'CheckIn',checkin_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
        <td><%= link_to 'CheckOut',checkout_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
        <td><%= link_to 'Reject',reject_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>


<%= link_to 'Back', admins_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Leasing Management System</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>