config/routes.rb
Rails.application.routes.draw do

  devise_for :applicants,controllers: { sessions: 'applicants/sessions', registrations: 'applicants/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :leasing_agents, controllers: { sessions: 'leasing_agents/sessions', registrations: 'leasing_agents/registrations'}


  resources :waitlists
  resources :applications
  resources :properties
  resources :admins
  resources :applicants
  resources :leasing_agents
  root 'home#index'
  devise_scope :leasing_agents do
    get '/users/sign_out' => 'devise/sessions#destroy'
    end
    devise_scope :admin do
      get '/admin/sign_out' => 'devise/sessions#destroy'
    end
  devise_scope :applicants do
    get '/applicants/sign_out' => 'devise/sessions#destroy'
  end


  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'getallProperties' => 'properties#getallproperties', :as => :getallproperties
  get 'tenantcheckin' => 'properties#checkin', :as => :tenantcheckin
  get 'tenantcheckout' => 'properties#checkout', :as => :tenantcheckout
  get 'tenantapproval' => 'properties#approval', :as => :tenantapproval
  get '/show_leasing_agents' => 'admins#show_leasing_agents', :as => 'show_leasing_agents'
  get '/show_properties' => 'admins#show_properties', :as => 'show_properties'
  get '/show_applicants' => 'admins#show_applicants', :as => 'show_applicants'
  get '/show_applications' => 'admins#show_applications', :as => 'show_applications'
  get '/add_applications' => 'applications#admin_application', :as => 'add_applications'
  get '/add_properties' => 'properties#admin_properties', :as => 'add_properties'

  get 'getproperties' => 'leasing_agents#getproperties', :as => :getproperties
  get 'checkin' => 'applications#checkin', :as => :checkin
  get 'checkout' => 'applications#checkout', :as => :checkout
  get 'reject' => 'applications#reject', :as => :reject

  get 'moveout'=> 'properties#moveout', :as => :moveout

end

app/models/property.rb
class Property < ApplicationRecord
  has_many :applications
  has_many :applicants, through: :applications, dependent: :destroy
  belongs_to :leasing_agent, optional: true
  validates :name, :address, :size, :terms_available, :earliest_start_time, :application_fee, :monthly_rent, :occupied_by, presence: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: [:show, :edit, :update, :destroy]

  # GET /properties or /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1 or /properties/1.json
  def show
    @property = Property.find(params[:id])
    @applications = Application.where('property_id = ?', @property.id)
  end

  def moveout
    @property = Property.find(params[:property_id])
    @property.availability = true
    @property.occupied_by = 'none'
    @property.occupant_id = 0
    @property.save
    respond_to do |format|
      format.html { redirect_to applicants_path, notice: "Moved out successfully." }
    end
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    create_params = property_params
    if leasing_agent_signed_in?
    create_params[:leasing_agent_id] = current_leasing_agent.id
    end

    @property = Property.new(create_params)


    respond_to do |format|
      if @property.save
        if leasing_agent_signed_in?
          format.html { redirect_to @property, notice: "Property was successfully created." }
          format.json { render :showproperties, status: :created, location: @property }
        else
        format.html { redirect_to @property, notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to @property, notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      if admin_signed_in?
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      else
        format.html { redirect_to getproperties_path, notice: "Property was successfully destroyed." }
      end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      # params.require(:property).permit(:name, :address, :size, :features_pets, :features_laundry, :features_parking, :terms_available, :earliest_start_time, :application_fee, :monthly_rent, :occupied_by, :leasing_agent_id)
      params.require(:property).permit(:name, :address, :size, :features_pets, :features_laundry, :features_parking, :terms_available, :earliest_start_time, :application_fee, :monthly_rent, :occupied_by, :availability, :leasing_agent_id)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :features_pets %>
    <%= form.check_box :features_pets %>
  </div>

  <div class="field">
    <%= form.label :features_laundry %>
    <%= form.check_box :features_laundry %>
  </div>

  <div class="field">
    <%= form.label :features_parking %>
    <%= form.check_box :features_parking %>
  </div>

  <div class="field">
    <%= form.label :terms_available %>
    <%= form.text_field :terms_available %>
  </div>

  <div class="field">
    <%= form.label :earliest_start_time %>
    <%= form.datetime_select :earliest_start_time %>
  </div>

  <div class="field">
    <%= form.label :application_fee %>
    <%= form.number_field :application_fee %>
  </div>

  <div class="field">
    <%= form.label :monthly_rent %>
    <%= form.number_field :monthly_rent %>
  </div>

  <div class="field">
    <%= form.label :occupied_by %>
    <%= form.text_field :occupied_by %>
  </div>

  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>

<% end %>

app/views/properties/admin_properties.html.erb
<%= form_with(model: Property) do |form| %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :features_pets %>
    <%= form.check_box :features_pets %>
  </div>

  <div class="field">
    <%= form.label :features_laundry %>
    <%= form.check_box :features_laundry %>
  </div>

  <div class="field">
    <%= form.label :features_parking %>
    <%= form.check_box :features_parking %>
  </div>

  <div class="field">
    <%= form.label :terms_available %>
    <%= form.text_field :terms_available %>
  </div>

  <div class="field">
    <%= form.label :earliest_start_time %>
    <%= form.datetime_select :earliest_start_time %>
  </div>

  <div class="field">
    <%= form.label :application_fee %>
    <%= form.number_field :application_fee %>
  </div>

  <div class="field">
    <%= form.label :monthly_rent %>
    <%= form.number_field :monthly_rent %>
  </div>

  <div class="field">
    <%= form.label :occupied_by %>
    <%= form.text_field :occupied_by %>
  </div>
  <div class="field">
    <%= form.label :leasing_agent_id %>
    <% leasing_agent_array = LeasingAgent.all.map { |leasingagent| [leasingagent.name, leasingagent.id] } %>
    <%= form.select(:leasing_agent_id, options_for_select(leasing_agent_array)) %>
  </div>
  <div class="field">
    <%= form.label :availability %>
    <%= form.check_box :availability %>
  </div>
  <div class="actions">
    <%= form.submit "Create" %>
  </div>



<% end %>
<%= link_to 'Back', :back %>

app/views/properties/edit.html.erb
<h1>Editing Property</h1>

<%= render 'form', property: @property %>

<%= link_to 'Show', @property %> |
<% if admin_signed_in? %>
  <%= link_to 'Back', show_properties_path %>
<% else %>
  <%= link_to 'Back', properties_path %>
<% end %>

app/views/properties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Properties</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Size</th>
      <th>Features pets</th>
      <th>Features laundry</th>
      <th>Features parking</th>
      <th>Terms available</th>
      <th>Earliest start time</th>
      <th>Application fee</th>
      <th>Monthly rent</th>
      <th>Occupied by</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.size %></td>
        <td><%= property.features_pets %></td>
        <td><%= property.features_laundry %></td>
        <td><%= property.features_parking %></td>
        <td><%= property.terms_available %></td>
        <td><%= property.earliest_start_time %></td>
        <td><%= property.application_fee %></td>
        <td><%= property.monthly_rent %></td>
        <td><%= property.occupied_by %></td>
        <td><%= property.availability %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path %>
<% if admin_signed_in? %>
  <%= link_to 'Back', admins_path %>
  <% else %>
<%= link_to 'Back', :back %>
<% end %>

app/views/properties/new.html.erb
<h1>New Property</h1>

<%= render 'form', property: @property %>

<% if leasing_agent_signed_in? %>
  <%= link_to 'Back', getproperties_path %>
<% else %>
<%= link_to 'Back', properties_path %>
<%end %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @property.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @property.address %>
</p>

<p>
  <strong>Size:</strong>
  <%= @property.size %>
</p>

<p>
  <strong>Features pets:</strong>
  <%= @property.features_pets %>
</p>

<p>
  <strong>Features laundry:</strong>
  <%= @property.features_laundry %>
</p>

<p>
  <strong>Features parking:</strong>
  <%= @property.features_parking %>
</p>

<p>
  <strong>Terms available:</strong>
  <%= @property.terms_available %>
</p>

<p>
  <strong>Earliest start time:</strong>
  <%= @property.earliest_start_time %>
</p>

<p>
  <strong>Application fee:</strong>
  <%= @property.application_fee %>
</p>

<p>
  <strong>Monthly rent:</strong>
  <%= @property.monthly_rent %>
</p>

<p>
  <strong>Occupied by:</strong>
  <%= @property.occupied_by %>
</p>

<p>
  <strong>Availability:</strong>
  <%= @property.availability %>
</p>
<br>

<%= link_to 'Edit', edit_property_path(@property) %> |
<% if admin_signed_in? %>
  <%= link_to 'Back', :back %>
<%else %>
  <%= link_to 'Back', getproperties_path%>

<% if leasing_agent_signed_in? %>
<h1> Applications for this Property</h1>
<br>

<table>
  <thead>
  <tr>
    <th>Applicant Name</th>
    <th>Date time</th>
    <th>Property</th>
    <th>Status</th>
    </div>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @applications.each do |application| %>
    <tr>
      <td><%= Applicant.find(application.applicant_id).name %></td>
      <td><%= application.date_time %></td>
      <td><%= Property.find(application.property_id).name %></td>
      <td><%= application.status %></td>
      <td><%= link_to 'CheckIn',checkin_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
      <td><%= link_to 'CheckOut',checkout_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
      <td><%= link_to 'Reject',reject_path(:id=>application.id,:applicant_id=>application.applicant_id,:property_id=>application.property_id) %></td>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<br>

<%end %>