config/routes.rb
Rails.application.routes.draw do

  devise_for :applicants,controllers: { sessions: 'applicants/sessions', registrations: 'applicants/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :leasing_agents, controllers: { sessions: 'leasing_agents/sessions', registrations: 'leasing_agents/registrations'}


  resources :waitlists
  resources :applications
  resources :properties
  resources :admins
  resources :applicants
  resources :leasing_agents
  root 'home#index'
  devise_scope :leasing_agents do
    get '/users/sign_out' => 'devise/sessions#destroy'
    end
    devise_scope :admin do
      get '/admin/sign_out' => 'devise/sessions#destroy'
    end
  devise_scope :applicants do
    get '/applicants/sign_out' => 'devise/sessions#destroy'
  end


  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'getallProperties' => 'properties#getallproperties', :as => :getallproperties
  get 'tenantcheckin' => 'properties#checkin', :as => :tenantcheckin
  get 'tenantcheckout' => 'properties#checkout', :as => :tenantcheckout
  get 'tenantapproval' => 'properties#approval', :as => :tenantapproval
  get '/show_leasing_agents' => 'admins#show_leasing_agents', :as => 'show_leasing_agents'
  get '/show_properties' => 'admins#show_properties', :as => 'show_properties'
  get '/show_applicants' => 'admins#show_applicants', :as => 'show_applicants'
  get '/show_applications' => 'admins#show_applications', :as => 'show_applications'
  get '/add_applications' => 'applications#admin_application', :as => 'add_applications'
  get '/add_properties' => 'properties#admin_properties', :as => 'add_properties'

  get 'getproperties' => 'leasing_agents#getproperties', :as => :getproperties
  get 'checkin' => 'applications#checkin', :as => :checkin
  get 'checkout' => 'applications#checkout', :as => :checkout
  get 'reject' => 'applications#reject', :as => :reject

  get 'moveout'=> 'properties#moveout', :as => :moveout

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    if admin_signed_in?
      redirect_to admins_path

    elsif applicant_signed_in?
      redirect_to applicants_path

    elsif leasing_agent_signed_in?
      redirect_to leasing_agents_path
    end
  end

end

app/views/home/index.html.erb
<p id=”notice”><%= notice %></p>
<h1>Leasing Management System</h1>
<p>A property management tool</p>
<p class="navbar-text pull-right">
  <% if applicant_signed_in? %>
    Logged in as <strong> <%= current_applicant.email %></strong>.
    <%= link_to "Logout", destroy_applicant_session_path, method: :delete, :class => 'navbar-link'  %>
  <%end %>
</p>
<p class="navbar-text pull-right">
  <% if admin_signed_in? %>
    Logged in as <strong> <%= current_admin.email %></strong>.
    <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
  <%end %>
</p>
<h2 align="center">Please select a user category</h2>


<% if admin_signed_in? %>
  <h3 align="center"><%= link_to 'Admin', admins_path %></h3>
<% else %>
  <h3 align="center"><%= link_to 'Admin', new_admin_session_path %></h3>
<%end %>

<% if applicant_signed_in? %>
  <h3 align="center"><%= link_to 'Applicant', applicant_path %></h3>
<% else %>
  <h3 align="center"><%= link_to 'Applicant', new_applicant_session_path %></h3>
<% end %>

<% if leasing_agent_signed_in? %>
  <h3 align="center"><%= link_to 'Leasing Agent', leasing_agent_path %></h3>
<% else %>
  <h3 align="center"><%= link_to 'Leasing Agent', new_leasing_agent_session_path %></h3>
<% end %>