config/routes.rb
Rails.application.routes.draw do

  devise_for :applicants,controllers: { sessions: 'applicants/sessions', registrations: 'applicants/registrations'}
  devise_for :admins, controllers: { sessions: 'admins/sessions', registrations: 'admins/registrations'}
  devise_for :leasing_agents, controllers: { sessions: 'leasing_agents/sessions', registrations: 'leasing_agents/registrations'}


  resources :waitlists
  resources :applications
  resources :properties
  resources :admins
  resources :applicants
  resources :leasing_agents
  root 'home#index'
  devise_scope :leasing_agents do
    get '/users/sign_out' => 'devise/sessions#destroy'
    end
    devise_scope :admin do
      get '/admin/sign_out' => 'devise/sessions#destroy'
    end
  devise_scope :applicants do
    get '/applicants/sign_out' => 'devise/sessions#destroy'
  end


  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'getallProperties' => 'properties#getallproperties', :as => :getallproperties
  get 'tenantcheckin' => 'properties#checkin', :as => :tenantcheckin
  get 'tenantcheckout' => 'properties#checkout', :as => :tenantcheckout
  get 'tenantapproval' => 'properties#approval', :as => :tenantapproval
  get '/show_leasing_agents' => 'admins#show_leasing_agents', :as => 'show_leasing_agents'
  get '/show_properties' => 'admins#show_properties', :as => 'show_properties'
  get '/show_applicants' => 'admins#show_applicants', :as => 'show_applicants'
  get '/show_applications' => 'admins#show_applications', :as => 'show_applications'
  get '/add_applications' => 'applications#admin_application', :as => 'add_applications'
  get '/add_properties' => 'properties#admin_properties', :as => 'add_properties'

  get 'getproperties' => 'leasing_agents#getproperties', :as => :getproperties
  get 'checkin' => 'applications#checkin', :as => :checkin
  get 'checkout' => 'applications#checkout', :as => :checkout
  get 'reject' => 'applications#reject', :as => :reject

  get 'moveout'=> 'properties#moveout', :as => :moveout

end

app/models/leasing_agent.rb
class LeasingAgent < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :properties
  validates :name, :email, :phone_number, presence: true
  validates :password, presence: true, :if =>:password


end

app/controllers/leasing_agents/confirmations_controller.rb
# frozen_string_literal: true

class LeasingAgents::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/leasing_agents/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class LeasingAgents::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/leasing_agents/passwords_controller.rb
# frozen_string_literal: true

class LeasingAgents::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/leasing_agents/registrations_controller.rb
# frozen_string_literal: true

class LeasingAgents::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  #before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :phone_number, :email, :password])
  end

  #If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :phone_number, :email, :password])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    '/leasing_agents'
  end
  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  #end
end

app/controllers/leasing_agents/sessions_controller.rb
# frozen_string_literal: true

class LeasingAgents::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected
  def after_sign_in_path_for(resource)
    "/leasing_agents"
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/leasing_agents/unlocks_controller.rb
# frozen_string_literal: true

class LeasingAgents::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/leasing_agents_controller.rb
class LeasingAgentsController < ApplicationController

  before_action :set_leasing_agent, only: [:show, :edit, :update, :destroy]


  # get list of properties
  def getproperties
    #@properties = Property.all
    @properties = Property.where('leasing_agent_id = ?', current_leasing_agent.id)
  end

  # GET /leasing_agents or /leasing_agents.json
  def index
    if admin_signed_in?
      redirect_to show_leasing_agents_path
      end
      @leasing_agents = LeasingAgent.all
  end

  # GET /leasing_agents/1 or /leasing_agents/1.json
  def show

  end

  # GET /leasing_agents/new
  def new
    @leasing_agent = LeasingAgent.new
  end

  # GET /leasing_agents/1/edit
  def edit
    @leasing_agent = LeasingAgent.find(params[:id])
  end

  # POST /leasing_agents or /leasing_agents.json
  def create
    @leasing_agent = LeasingAgent.new(leasing_agent_params)
    respond_to do |format|
      if @leasing_agent.save
        format.html { redirect_to @leasing_agent, notice: "Leasing agent was successfully created." }
        format.json { render :show, status: :created, location: @leasing_agent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @leasing_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leasing_agents/1 or /leasing_agents/1.json
  def update
    @leasing_agent = LeasingAgent.find(params[:id])
    respond_to do |format|
      if @leasing_agent.update(leasing_agent_params)
        format.html { redirect_to show_leasing_agents_path, notice: "Leasing agent was successfully updated." }
        format.json { render :show, status: :ok, location: @leasing_agent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @leasing_agent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leasing_agents/1 or /leasing_agents/1.json
  def destroy
    @leasing_agent.destroy
    respond_to do |format|
      format.html { redirect_to show_leasing_agents_path, notice: "Leasing agent was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_leasing_agent
      @leasing_agent = LeasingAgent.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def leasing_agent_params
      params.require(:leasing_agent).permit(:name, :password, :email, :phone_number)
    end
end

app/helpers/leasing_agents_helper.rb
module LeasingAgentsHelper
end

app/views/leasing_agents/_form.html.erb
<%= form_with(model: leasing_agent) do |form| %>
  <% if leasing_agent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(leasing_agent.errors.count, "error") %> prohibited this leasing_agent from being saved:</h2>

      <ul>
        <% leasing_agent.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/leasing_agents/edit.html.erb
<h1>Editing Leasing Agent</h1>

<%= render 'form', leasing_agent: @leasing_agent %>

<% if current_admin.nil? %>
  <%= link_to 'Show', @leasing_agent %> |
  <%= link_to 'Back', leasing_agents_path %>
<% else %>
  <%= link_to 'Back', leasing_agents_path %>
<% end %>

app/views/leasing_agents/getproperties.html.erb
<p id="notice"><%= notice %></p>
<p align="right" class="navbar-text pull-left">
  <% if leasing_agent_signed_in? %>
    Logged in as <strong> <%= current_leasing_agent.email %></strong>.
    <%= link_to "Sign out", destroy_leasing_agent_session_path, method: :get, :class => 'navbar-link'  %>
    <%= link_to 'Edit profile', edit_leasing_agent_registration_path,  :class => 'navbar-link' %>
  <%end %>
</p>
<% if leasing_agent_signed_in? %>
  <h1><%= current_leasing_agent.name %>'s Leasing Agents Dashboard</h1>

<%end %>

<% if leasing_agent_signed_in? %>
  <h2>Click on Show to view the applications associated with the properties</h2>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Size</th>
      <th>Features pets</th>
      <th>Features laundry</th>
      <th>Features parking</th>
      <th>Terms available</th>
      <th>Earliest start time</th>
      <th>Application fee</th>
      <th>Monthly rent</th>
      <th>Occupied by</th>
      <th>Availability</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @properties.each do |property| %>
      <tr>
        <td><%= property.name %></td>
        <td><%= property.address %></td>
        <td><%= property.size %></td>
        <td><%= property.features_pets %></td>
        <td><%= property.features_laundry %></td>
        <td><%= property.features_parking %></td>
        <td><%= property.terms_available %></td>
        <td><%= property.earliest_start_time %></td>
        <td><%= property.application_fee %></td>
        <td><%= property.monthly_rent %></td>
        <td><%= property.occupied_by %></td>
        <td><%= property.availability %></td>
        <td><%= link_to 'Show', property %></td>
        <td><%= link_to 'Edit', edit_property_path(property) %></td>
        <td><%= link_to 'Remove', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Property', new_property_path %>
  <%= link_to 'Back', leasing_agents_path %>
<%end %>

<br>

<%#= link_to 'New Leasing Agent', new_leasing_agent_path %>

app/views/leasing_agents/index.html.erb
<p id="notice"><%= notice %></p>
<p align="right" class="navbar-text pull-left">
  <% if leasing_agent_signed_in? %>
    Logged in as <strong> <%= current_leasing_agent.email %></strong>.
    <%= link_to "Sign out", destroy_leasing_agent_session_path, method: :get, :class => 'navbar-link'  %>
    <%= link_to 'Edit profile', edit_leasing_agent_registration_path,  :class => 'navbar-link' %>
  <%end %>
</p>
<% if leasing_agent_signed_in? %>
<h1><%= current_leasing_agent.name %>'s Leasing Agents Dashboard</h1>
  <%= link_to 'Click here to View and Add Properties', getproperties_path %>
<%end %>

<% if leasing_agent_signed_in? %>
  <table>
    <thead>
    <tr>
      <th></th>
      <th colspan="3"></th>
    </tr>
    </thead>

  </table>
<%end %>

<br>

<%#= link_to 'View Properties', getproperties_path %>

<%#= link_to 'New Leasing Agent', new_leasing_agent_path %>

app/views/leasing_agents/new.html.erb
<h1>New Leasing Agent</h1>

<%= render 'form', leasing_agent: @leasing_agent %>

<%= link_to 'Back', root_path %>

app/views/leasing_agents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @leasing_agent.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @leasing_agent.password %>
</p>

<p>
  <strong>Email address:</strong>
  <%= @leasing_agent.email_address %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @leasing_agent.phone_number %>
</p>

<%= link_to 'Edit', edit_leasing_agent_path(@leasing_agent) %> |
<%= link_to 'Back', leasing_agents_path %>

app/views/leasing_agents/signup.html.erb
<%= form_with(model: LeasingAgent, local: true) do |form| %>
<h2>Sign Up for Leasing Agent</h2>

  <div class="field">
    <%= form.label 'Name' %>
    <%= form.text_field :name_field %>
  </div>
  <div class="field">
    <%= form.label 'Phone number' %>
    <%= form.text_field :phone_field %>
  </div>
  <div class="field">
    <%= form.label 'Email ID' %>
    <%= form.text_field :email_field %>
  </div>

  <div class="field">
    <%= form.label 'Password' %>
    <%= form.text_field :password_field %>
  </div>


<% end %>